// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/change-password": {
            "post": {
                "description": "Change user password by inputting the current password and the new password.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Change user password.",
                "parameters": [
                    {
                        "description": "the body to change user password",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ChangePasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ChangePasswordResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Logging in to get jwt token to access admin or user api by roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login as user.",
                "parameters": [
                    {
                        "description": "the body to login a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginResponse"
                        }
                    }
                }
            }
        },
        "/phones": {
            "get": {
                "description": "Get a list of Phones",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phones"
                ],
                "summary": "List all phones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.AllPhoneResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a phone",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phones"
                ],
                "summary": "Create a phone",
                "parameters": [
                    {
                        "description": "the body to create a phone",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreatePhoneInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreatedPhoneResponse"
                        }
                    }
                }
            }
        },
        "/phones/{phone_id}": {
            "get": {
                "description": "Get phone details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phones"
                ],
                "summary": "Get phone details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PhoneID",
                        "name": "phone_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PhoneByIDResponse"
                        }
                    }
                }
            }
        },
        "/phones/{phone_id}/reviews": {
            "get": {
                "description": "Get all phone reviews by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phones"
                ],
                "summary": "Get all phone reviews by its ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PhoneID",
                        "name": "phone_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Review"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create phone review by phone ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phones"
                ],
                "summary": "Create a phone review by phone ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PhoneID",
                        "name": "phone_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to create phone review",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateReviewInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Review"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "registering a user from public access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a user.",
                "parameters": [
                    {
                        "description": "the body to register a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Register Success Response",
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/reviews": {
            "get": {
                "description": "Get a list of Reviews",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "List all reviews",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.AllReviewResponse"
                            }
                        }
                    }
                }
            }
        },
        "/reviews/{review_id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a review",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Update a review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ReviewID",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to edit phone review",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.EditReviewInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.EditReviewResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a review",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Delete a review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ReviewID",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.DeleteReviewResponse"
                        }
                    }
                }
            }
        },
        "/reviews/{review_id}/comment": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a review comment by review ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Create a review comment by review ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ReviewID",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to create phone review",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateCommentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateCommentResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AllPhoneResponse": {
            "type": "object",
            "properties": {
                "phone_id": {
                    "type": "integer",
                    "x-order": "0",
                    "example": 1
                },
                "brand": {
                    "type": "string",
                    "x-order": "1",
                    "example": "Samsung"
                },
                "model": {
                    "type": "string",
                    "x-order": "2",
                    "example": "Galaxy"
                },
                "release_date": {
                    "type": "string",
                    "x-order": "3",
                    "example": "2023-11-11T00:00:00+07:00"
                },
                "price": {
                    "type": "integer",
                    "x-order": "4",
                    "example": 10000
                },
                "image_url": {
                    "type": "string",
                    "x-order": "5",
                    "example": ""
                }
            }
        },
        "controllers.AllReviewResponse": {
            "type": "object",
            "properties": {
                "review_id": {
                    "type": "integer",
                    "x-order": "0",
                    "example": 1
                },
                "phone_id": {
                    "type": "integer",
                    "x-order": "1",
                    "example": 1
                },
                "user_id": {
                    "type": "integer",
                    "x-order": "3",
                    "example": 1
                },
                "rating": {
                    "type": "integer",
                    "x-order": "4",
                    "example": 1
                },
                "review_text": {
                    "type": "string",
                    "x-order": "5",
                    "example": "this is sample text"
                },
                "created_at": {
                    "type": "string",
                    "x-order": "6",
                    "example": ""
                },
                "phone": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/controllers.PhoneResponse"
                        }
                    ],
                    "x-order:2": true
                }
            }
        },
        "controllers.ChangePasswordInput": {
            "type": "object",
            "required": [
                "confirm_new_password",
                "current_password",
                "new_password",
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "x-order": "0",
                    "example": "admin"
                },
                "current_password": {
                    "type": "string",
                    "x-order": "1",
                    "example": "admin"
                },
                "new_password": {
                    "type": "string",
                    "x-order": "2",
                    "example": "admin1"
                },
                "confirm_new_password": {
                    "type": "string",
                    "x-order": "3",
                    "example": "admin1"
                }
            }
        },
        "controllers.ChangePasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "change password success"
                }
            }
        },
        "controllers.CreateCommentInput": {
            "type": "object",
            "required": [
                "comment_text"
            ],
            "properties": {
                "comment_text": {
                    "type": "string",
                    "example": "this review is rigged!"
                }
            }
        },
        "controllers.CreateCommentResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "x-order": "0",
                    "example": "comment created successfully"
                },
                "comments": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Comment"
                        }
                    ],
                    "x-order": "1"
                }
            }
        },
        "controllers.CreatePhoneInput": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "x-order": "1",
                    "example": "Samsung"
                },
                "model": {
                    "type": "string",
                    "x-order": "2",
                    "example": "Galaxy"
                },
                "release_date": {
                    "type": "string",
                    "x-order": "3",
                    "example": "2023-01-01T00:00:00Z"
                },
                "price": {
                    "type": "integer",
                    "x-order": "4",
                    "example": 10000
                },
                "image_url": {
                    "type": "string",
                    "x-order": "5",
                    "example": ""
                }
            }
        },
        "controllers.CreateReviewInput": {
            "type": "object",
            "required": [
                "rating",
                "review_text"
            ],
            "properties": {
                "rating": {
                    "type": "integer",
                    "example": 1
                },
                "review_text": {
                    "type": "string",
                    "example": "sample review text"
                }
            }
        },
        "controllers.CreatedPhoneResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "x-order": "0",
                    "example": "phone created successfully"
                },
                "phone": {
                    "type": "object",
                    "properties": {
                        "phone_id": {
                            "type": "integer",
                            "x-order": "0",
                            "example": 1
                        },
                        "brand": {
                            "type": "string",
                            "x-order": "1",
                            "example": "Samsung"
                        },
                        "model": {
                            "type": "string",
                            "x-order": "2",
                            "example": "Galaxy"
                        },
                        "release_date": {
                            "type": "string",
                            "x-order": "3",
                            "example": "2023-01-01T00:00:00Z"
                        },
                        "price": {
                            "type": "integer",
                            "x-order": "4",
                            "example": 10000
                        },
                        "image_url": {
                            "type": "string",
                            "x-order": "5",
                            "example": ""
                        }
                    },
                    "x-order": "1"
                }
            }
        },
        "controllers.DeleteReviewResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "x-order": "0",
                    "example": "review deleted successfully"
                }
            }
        },
        "controllers.EditReviewInput": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer",
                    "example": 1
                },
                "review_text": {
                    "type": "string",
                    "example": "sample review text"
                }
            }
        },
        "controllers.EditReviewResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "x-order": "0",
                    "example": "review updated successfully"
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Review"
                    },
                    "x-order": "1"
                }
            }
        },
        "controllers.LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "x-order": "0",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "x-order": "1",
                    "example": "admin"
                }
            }
        },
        "controllers.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "x-order": "0",
                    "example": "login success"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string",
                            "example": "john@example.com"
                        },
                        "role": {
                            "type": "string",
                            "example": "user"
                        },
                        "username": {
                            "type": "string",
                            "example": "John"
                        }
                    },
                    "x-order": "1"
                },
                "token": {
                    "type": "string",
                    "x-order": "2",
                    "example": "string"
                }
            }
        },
        "controllers.PhoneByIDResponse": {
            "type": "object",
            "properties": {
                "phone_id": {
                    "type": "integer",
                    "x-order": "0",
                    "example": 1
                },
                "brand": {
                    "type": "string",
                    "x-order": "1",
                    "example": "Samsung"
                },
                "model": {
                    "type": "string",
                    "x-order": "2",
                    "example": "Galaxy"
                },
                "release_date": {
                    "type": "string",
                    "x-order": "3",
                    "example": "2023-11-11"
                },
                "price": {
                    "type": "integer",
                    "x-order": "4",
                    "example": 10000
                },
                "image_url": {
                    "type": "string",
                    "x-order": "5",
                    "example": ""
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.ReviewResponse"
                    },
                    "x-order": "6"
                }
            }
        },
        "controllers.PhoneResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Samsung"
                },
                "image_url": {
                    "type": "string",
                    "example": ""
                },
                "model": {
                    "type": "string",
                    "example": "Galaxy"
                },
                "phone_id": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "integer",
                    "example": 10000
                },
                "release_date": {
                    "type": "string",
                    "example": "2023-11-11"
                }
            }
        },
        "controllers.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role",
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "x-order": "0",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "x-order": "1",
                    "example": "admin"
                },
                "email": {
                    "type": "string",
                    "x-order": "2",
                    "example": "admin@mail.com"
                },
                "role": {
                    "type": "string",
                    "x-order": "3",
                    "example": "Admin"
                }
            }
        },
        "controllers.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "x-order": "0",
                    "example": "registration success"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string",
                            "example": "john@example.com"
                        },
                        "role": {
                            "type": "string",
                            "example": "Admin"
                        },
                        "username": {
                            "type": "string",
                            "example": "John"
                        }
                    },
                    "x-order": "1"
                }
            }
        },
        "controllers.ReviewResponse": {
            "type": "object",
            "properties": {
                "phone_id": {
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "type": "integer",
                    "example": 9
                },
                "review_id": {
                    "type": "integer",
                    "example": 1
                },
                "review_text": {
                    "type": "string",
                    "example": "product is nice"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Comment": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "comment_text": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Like"
                    }
                },
                "review_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Like": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "like_id": {
                    "type": "integer"
                },
                "review_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Review": {
            "type": "object",
            "properties": {
                "review_id": {
                    "type": "integer",
                    "x-order": "0"
                },
                "phone_id": {
                    "type": "integer",
                    "x-order": "1"
                },
                "user_id": {
                    "type": "integer",
                    "x-order": "2"
                },
                "rating": {
                    "type": "integer",
                    "x-order": "3"
                },
                "review_text": {
                    "type": "string",
                    "x-order": "4"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Comment"
                    },
                    "x-order": "5"
                },
                "created_at": {
                    "type": "string",
                    "x-order": "5"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Like"
                    },
                    "x-order": "6"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
